image:
  registry: docker.io
  repository: mysql
  tag: "8.0"

auth:
  rootPassword: "gitea-root-password"
  database: "gitea"
  username: "gitea"
  password: "gitea-password"

primary:
  persistence:
    enabled: true
    size: 10Gi